# @package _global_
defaults:
  - /habitat: habitat_config_base

  - /habitat/simulator: isaac_rearrange_sim
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_head_rgbd_arm_agent
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: fetch_suction

  - /habitat/task: task_config_base
  - /habitat/task/rearrange/actions: fetch_suction_arm_base_empty
  - /habitat/task/measurements:
    - articulated_agent_force # TODO: jimmy: remove this since AttributeError: 'IsaacAgentData' object has no attribute 'grasp_mgr
    - articulated_agent_colls # TODO: jimmy: the underlying implementation is a hack
    - force_terminate # TODO: jimmy: the underlying implementation is a hack
    #- zero
    - end_effector_to_object_distance
    - end_effector_to_rest_distance
    - num_steps
    - art_obj_state
    - art_obj_at_desired_state
    - does_want_terminate
    - art_obj_success
    - art_obj_reward
  - /habitat/task/lab_sensors:
    - joint_sensor
    - hand_joint_sensor
    - target_start_sensor # Relative position from end effector to target object
    - end_effector_sensor
    - relative_resting_pos_sensor
    - door_orientation_sensor

  - /habitat/dataset/rearrangement: replica_cad
  - _self_

# Config for empty task to explore the scene.
habitat:
  gym:
    obs_keys:
      - articulated_agent_arm_depth
      - joint
      - hand_joint
      - obj_start_sensor # Relative position from end effector to target object
      - relative_resting_position
      - door_orientation
  task:
    # Config for empty task to explore the scene.
    type: RearrangePickTask-v0
    count_obj_collisions: True
    desired_resting_position: [0.5, 0.0, 1.0]
    # reward_measure: "zero" #  default measure for the play yaml
    # success_measure: "zero" #  default measure for the play yaml

    reward_measure: art_obj_reward
    success_measure: art_obj_success

    # Reach task config
    render_target: True
    ee_sample_factor: 0.8

    # In radians
    base_angle_noise: 0.0
    base_noise: 0.0
    constraint_violation_ends_episode: False

    force_regenerate: True
  environment:
    max_episode_steps: 0
  simulator:
    #type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - "data/objects/ycb/configs/"
    agents:
      main_agent:
        radius: 0.3
        sim_sensors:
          head_rgb_sensor:
            height: 128
            width: 128
          head_depth_sensor:
            height: 128
            width: 128
          arm_depth_sensor:
            height: 128
            width: 128
          arm_rgb_sensor:
            height: 128
            width: 128
    habitat_sim_v0:
      enable_physics: False
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
