# @package _global_

defaults:
  - hitl_defaults
  - _self_

habitat_hitl:
  driver: "HitlBareSimDriver"
  disable_policies_and_stepping: True
  window:
    title: "Sim Viewer"

sim_viewer:
  dataset: "data/hssd-hab/hssd-hab-articulated.scene_dataset_config.json"
  scene: "102817140.scene_instance.json"