# @package _global_

#This config file can be hot-reloaded with 'T' to quickly change robot settings

#global robot settings
# urdf: "data/hab_murp/murp_tmr_franka/franka_with_hand_v2.urdf"
usd: "data/usd/robots/franka_with_hand_v2.1.usda"
#NOTE: this is used to construct a prim path within the world
robot_prim_path_name: "Murp"

#what radius is required to represent the robot on the navmesh
navmesh_radius: 0.45
navmesh_height: 1.2
#how much extra clearance to add between navmesh heights and base position heights
ground_to_base_offset: 0.0

#offset from the robot's origin of the XR "head" viewpoint in local space
viewpoint_offset: [0.25,0,1.1]

#joint motor settings
create_joint_motors: True
max_joint_velocity: 200
angular_drive_stiffness: 100 #position gain
angular_drive_damping: 1 #velocity gain
angular_drive_max_force: 5000 #max force/torque
linear_drive_stiffness: 1000 #position gain
angular_damping: 1
linear_damping: 5

#base velocity controller settings
max_linear_speed: 1.0 #m/s
max_angular_speed: 1.0 #rad/sec
track_waypoints: True


configuration_subsets:
  #define the hand and arm joint indices
  #NOTE: we assume these are in the same order such that setting a symmetric pose is straightforward
  left_arm: [
            "left_fr3_joint1",
            "left_fr3_joint2",
            "left_fr3_joint3",
            "left_fr3_joint4",
            "left_fr3_joint5",
            "left_fr3_joint6",
            "left_fr3_joint7",
        ]
  right_arm: [
            "right_fr3_joint1",
            "right_fr3_joint2",
            "right_fr3_joint3",
            "right_fr3_joint4",
            "right_fr3_joint5",
            "right_fr3_joint6",
            "right_fr3_joint7",
        ]
  left_hand: [
            "joint_l_0_0",
            "joint_l_1_0",
            "joint_l_2_0",
            "joint_l_3_0",
            "joint_l_4_0",
            "joint_l_5_0",
            "joint_l_6_0",
            "joint_l_7_0",
            "joint_l_8_0",
            "joint_l_9_0",
            "joint_l_10_0",
            "joint_l_11_0",
            "joint_l_12_0",
            "joint_l_13_0",
            "joint_l_14_0",
            "joint_l_15_0"
        ]
  right_hand: [
            "joint_0_0",
            "joint_1_0",
            "joint_2_0",
            "joint_3_0",
            "joint_4_0",
            "joint_5_0",
            "joint_6_0",
            "joint_7_0",
            "joint_8_0",
            "joint_9_0",
            "joint_10_0",
            "joint_11_0",
            "joint_12_0",
            "joint_13_0",
            "joint_14_0",
            "joint_15_0"
        ]

link_subsets:
  #link ixs for finger tips on each hand
  left_thumb_tip: ["link_l15_0_digit2_sensor_base","link_l15_0_tip"]
  right_thumb_tip: ["link_15_0_digit2_sensor_base","link_15_0_tip"]
  #[index, middle, ring]
  right_finger_tips: ["link_3_0_digit2_sensor_base","link_3_0_tip", "link_7_0_digit2_sensor_base","link_7_0_tip", "link_11_0_digit2_sensor_base","link_11_0_tip"]
  left_finger_tips: ["link_l3_0_digit2_sensor_base","link_l3_0_tip", "link_l7_0_digit2_sensor_base", "link_l7_0_tip", "link_l11_0_digit2_sensor_base", "link_l11_0_tip"]
  #arm base links (the fixed attachment point)
  left_arm_base: ["left_fr3_link0"]
  right_arm_base: ["right_fr3_link0"]



#initial pose options. This refers to an entry in the robot_poses.json file.
initial_pose: "initial"
