# @package _global_

defaults:
  - social_rearrange: pop_play
  - hitl_defaults
  - _self_

habitat:
  # todo: document these choices
  environment:
    max_episode_steps: 0
    iterator_options:
      cycle: False
  task:
    measurements:
      pddl_success:
        must_call_stop: False

habitat_baselines:
  # todo: document these choices
  eval:
    should_load_ckpt: False
  rl:
    agent:
      num_pool_agents_per_type: [1,1]

habitat_hitl:
  window:
    title: "Rearrange"
    width: 1300
    height: 1000
  gui_controlled_agents:
    - agent_index: 1
      lin_speed: 10.0
      ang_speed: 300
  data_collection:
    save_filepath_base: "my_session"
    save_gfx_replay_keyframes: True
    save_episode_record: True
  hide_humanoid_in_gui: True
  camera:
    first_person_mode: True



rearrange:
  # Shows an intro sequence before the first episode that helps familiarize the user to task in a HITL context.
  show_tutorial: True
