data_path: "/fsx-siro/jtruong/repos/vla-physics/habitat-lab/data/"
urdf_path: "murp/murp/platforms/franka_tmr/franka_description_tmr/urdf/franka_with_hand_2_vyshnav.urdf"
arm_urdf_path: "murp/murp/platforms/franka_tmr/franka_description_tmr/urdf/franka_right_arm.urdf"
usda_path: "usd/robots/franka_with_hand_right.usda"

episode_json: "/fsx-siro/jtruong/repos/vla-physics/habitat-lab/habitat-lab/habitat/tasks/rearrange/task_pick.json.gz"

skill: "pick"
instruction: "Pick the object"
target_name: "fridge"
hand: "right"
policy_cls: "OraclePickPolicy"


grasp_cache_path: "/fsx-siro/jtruong/repos/vla-physics/habitat-lab/data/cache/initial_grasps/misc/dexgraspnet2.pth"
pick_ckpt_path: "/opt/hpcaas/.mounts/fs-03ee9f8c6dddfba21/jtruong/repos/gum_ws/src/GUM/results/experiment_8/run5/best_reward_3340.29.pth"