# @package _global_

defaults:
  - /habitat: habitat_config_base

  - /habitat/simulator: rearrange_sim
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: depth_head_agent
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: fetch_suction

  - /habitat/task: task_config_base
  - /habitat/task/rearrange/actions: fetch_suction_arm_base_stop
  - /habitat/task/measurements:
    - articulated_agent_force
    - force_terminate
    - articulated_agent_colls
    - object_to_goal_distance
    - num_steps
    - end_effector_to_object_distance
    - does_want_terminate
    - pddl_success
    - bad_called_terminate
    - did_violate_hold_constraint
    - move_objects_reward
  - /habitat/task/lab_sensors:
    - target_start_sensor
    - goal_sensor
    - joint_sensor
    - is_holding_sensor
    - end_effector_sensor
    - relative_resting_pos_sensor
    - target_start_gps_compass_sensor
    - target_goal_gps_compass_sensor
    - localization_sensor

  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    obs_keys:
      - head_depth
      - relative_resting_position
      - obj_start_sensor
      - obj_goal_sensor
      - obj_start_gps_compass
      - obj_goal_gps_compass
      - joint
      - is_holding
      - ee_pos
  task:
    type: RearrangePddlTask-v0
    reward_measure: move_obj_reward
    success_measure: pddl_success
    success_reward: 100.0
    slack_reward: -0.01
    end_on_success: True
    constraint_violation_ends_episode: False
    constraint_violation_drops_object: True
    task_spec: rearrange_easy
    measurements:
      force_terminate:
        max_accum_force: 100000.0
        max_instant_force: 10000.0
      move_objects_reward:
        force_pen: 0.0
  environment:
    max_episode_steps: 3000
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v2/{split}/rearrange_easy.json.gz
