# @package habitat.task.actions
defaults:
  - /habitat/task/actions:
    - arm_action
  - _self_
arm_action:
  type: "ArmAction"
  arm_controller: "ArmRelPosMaskAction"
  grip_controller: "GazeGraspAction"
  arm_joint_mask: [1,1,0,1,0,1,0]
  arm_joint_dimensionality: 4
  grasp_thresh_dist: 0.15
  disable_grip: False
  delta_pos_limit: 0.0872665
  ee_ctrl_lim: 0.015
  gaze_distance_range: [0.3, 0.75]
  center_cone_angle_threshold: 20.0