# Version of tidy house that only has two target objects.
objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  - name: TARGET_any_targets|0
    expr_type: goal_entity_type
  - name: any_targets|1
    expr_type: movable_entity_type
  - name: TARGET_any_targets|1
    expr_type: goal_entity_type
  - name: robot_0
    expr_type: robot_entity_type
  - name: robot_1
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    - object_at(any_targets|0,TARGET_any_targets|0)
    - object_at(any_targets|1,TARGET_any_targets|1)
    - not_holding(robot_0)
    - not_holding(robot_1)

stage_goals:
  stage_1_1:
    expr_type: AND
    sub_exprs:
      - quantifier: EXISTS
        inputs:
          - name: robot
            expr_type: robot_entity_type
        expr_type: AND
        sub_exprs:
          - holding(any_targets|0, robot)
  stage_1_2:
    expr_type: AND
    sub_exprs:
      - object_at(any_targets|0,TARGET_any_targets|0)
  stage_2_1:
    expr_type: AND
    sub_exprs:
      - quantifier: EXISTS
        inputs:
          - name: robot
            expr_type: robot_entity_type
        expr_type: AND
        sub_exprs:
          - holding(any_targets|1, robot)
  stage_2_2:
    expr_type: AND
    sub_exprs:
      - object_at(any_targets|1,TARGET_any_targets|1)

solution:
  - nav_to_goal(any_targets|1, robot_1)
  - pick(any_targets|1, robot_1)
  - nav_to_obj(TARGET_any_targets|1, robot_1)
  - place(any_targets|1,TARGET_any_targets|1, robot_1)
