# @package _global_

# Top-level configuration for running a headless HITL server in multi-user mode.

defaults:
  - lang_rearrange_spot_humanoid.yaml
  - server.yaml
  - _self_

habitat_hitl:
  networking:
    max_client_count: 2


rearrange_v2:
  highlight_default_receptacles: True
  agents:
    agent_0:
      head_sensor_substring: "head"
      can_change_object_states: True
    agent_1:
      head_sensor_substring: "jaw"
      can_change_object_states: False
