# @package _global_

# Top-level configuration for running a headless HITL server in single-user mode.

defaults:
  - lang_rearrange_spot_only.yaml
  - server.yaml
  - hitl_skills.yaml
  - _self_


rearrange_v2:
  highlight_default_receptacles: True
  agents:
    agent_0:
      head_sensor_substring: "head"
      can_change_object_states: True
