# @package _global_

# Top-level configuration for running a headless HITL server in single-user mode.

defaults:
  - lang_rearrange_spot_only.yaml
  - _self_


rearrange_v2:
  highlight_default_receptacles: True
  agents:
    main_agent:
      head_sensor_substring: "head"
      can_change_object_states: True

SHORT_CIRCUIT: True
habitat_hitl:
  networking:
    enable: True
    max_client_count: 1
