# @package _global_

defaults:
  - _self_

habitat_hitl:
  window: ~
  networking:
    enable: True
    max_client_count: 1
    http_availability_server:
      enable: True
    client_max_idle_duration: 180.0
    enable_connections_by_default: False
  experimental:
    headless:
      do_headless: True
